name: module_analyzer
description: module analyzer.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  analyzer: ^3.2.0
  analyzer_plugin: ^0.9.0
  quick_log: any
  path: any

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
